name: Bug Report
description: Create a bug report to aid us in making improvements to our application
labels: [ 'type:bug' ]
body:
  - type: markdown
    attributes:
      value: |
        ### :bug: &nbsp; Hello there, so you've found a bug 
        Please be as detailed as possible :smile:
        <br>

  - type: textarea
    id: location
    attributes:
      label: 📍 Location of bug
      description: Whereabouts did you encounter this issue (ie. page url and name) ?
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: ✏️ Description of bug
      description: Type out a detailed description of the bug
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: 🔁 Steps to Reproduce
      description: Type out detailed instructions for us to follow to reproduce this bug
      value: |
            1. .....
            2. ...   
    validations:
      required: true
  - type: textarea
    attributes:
      label: 📸 Screenshots
      description: | 
        Include any pictures / screenshots of the bug in action
        Drag any picture from your Finder/Desktop in the below text box provided
  - type: dropdown
    id: frequency
    attributes:
      label: ⏰ Bug frequency 
      description: How often are you experiencing the specified bug ?
      multiple: false
      options:
        - "Constant"
        - "Often"
        - "Irregular"
        - "Once or twice"
  - type: textarea
    id: useful-info-other
    attributes:
      label: ℹ️ Other useful information
      description: Please include any other necessary information about the bug you're experiencing.
      value: |
          Product Ids (if applicable): (ie. [ 10, RF5hY, 889FVVS ])
  - type: textarea
    id: reporter-details
    attributes:
      label: 👀   Reporter Details
      description: Please include your name and livtours email for us to identify the reporter
      value: |
         NAME: UPDATE_TEXT_HERE
         EMAIL: UPDATE_TEXT_HERE
  - type: markdown
    attributes:
        value:  |
          And you're done, thanks for catching this for us.
          Have a lovely day 🤗
